### ISSUE TITLE
invalid json example generating

### ISSUE THREAD

**Issue by flashpixx** [mrk-andreev/tornado-swagger#44]
**Describe the bug**
With this schema

```yaml
schema:
      type: array
      items:
            type: string
      example:
            - das ist ein langer deutscher Text
            - this is a huge english text
```

it generates this data and curl structure in the web interface

```
curl -X POST "http://localhost:7120/analysis/language" -H  "accept: application/json" -H  "Content-Type: application/json" -d ""
```

and the example

```
[
  "das ist ein langer deutscher Text",
  "this is a huge english text"
]
```

but on running with curl or directly from the ui interface it produces an error because the JSON is not valid

**To Reproduce**
add the code to a post route in a python documentation

**error structure**

it seems, that it is a quoting problem, because it generates strings with double quotes for each example item
